#!/bin/sh
#
# nghttp2 - HTTP/2 C Library
#
# Copyright (c) 2013 Tatsuhiro Tsujikawa
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

export ANDROID_HOME=/home/hanpfei0306/data/dev_tools/Android/android-ndk-r12b

if [ -z "$ANDROID_HOME" ]; then
    echo 'No $ANDROID_HOME specified.'
    exit 1
fi
PREFIX=/media/data/dev_tools/Android/android-ndk-r9d/platforms/android-15/arch-arm
TOOLCHAIN="$ANDROID_HOME"/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
PATH="$TOOLCHAIN"/bin:"$PATH"

./configure \
    --disable-shared \
    --host=arm-linux-androideabi \
    --build=`dpkg-architecture -qDEB_BUILD_GNU_TYPE` \
    --with-xml-prefix="$PREFIX" \
    --without-libxml2 \
    --disable-python-bindings \
    --disable-examples \
    CC=/home/hanpfei0306/data/dev_tools/Android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc \
    CXX=/home/hanpfei0306/data/dev_tools/Android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ \
    CPPFLAGS="-fPIE --sysroot=/media/data/dev_tools/Android/android-ndk-r9d/platforms/android-15/arch-arm -I/media/data/dev_tools/Android/android-ndk-r9d/platforms/android-15/arch-arm/usr/include" \
    PKG_CONFIG_LIBDIR="/home/hanpfei0306/data/dev_tools/Android/android-ndk-r12b/prebuilt/linux-x86_64/lib/pkgconfig" \
    LDFLAGS="-fPIE -pie -L/media/data/dev_tools/Android/android-ndk-r9d/platforms/android-15/arch-arm/usr/lib"
