# From CFLAG
LOCAL_CFLAGS += -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -march=armv7-a \
	-mandroid -I$(ANDROID_DEV)/include -B$(ANDROID_DEV)/lib -O3 -fomit-frame-pointer -Wall

# From DEPFLAG
LOCAL_CFLAGS += -DOPENSSL_NO_EC_NISTP_64_GCC_128 \
	-DOPENSSL_NO_GMP \
	-DOPENSSL_NO_JPAKE \
	-DOPENSSL_NO_LIBUNBOUND \
	-DOPENSSL_NO_MD2 \
	-DOPENSSL_NO_RC5 \
	-DOPENSSL_NO_RFC3779 \
	-DOPENSSL_NO_SCTP \
	-DOPENSSL_NO_SSL_TRACE \
	-DOPENSSL_NO_SSL2 \
	-DOPENSSL_NO_STORE \
	-DOPENSSL_NO_UNIT_TEST \
	-DOPENSSL_NO_WEAK_SSL_CIPHERS

# Extra
LOCAL_CFLAGS += -DZLIB -DOPENSSL_NO_HW -DOPENSSL_NO_GOST -DNO_WINDOWS_BRAINDEATH

LOCAL_CFLAGS += -DOPENSSL_NO_DEPRECATED
